### ISSUE TITLE
Template _HISTROY.md is required but the actual file name is _Histroy.md

### ISSUE THREAD

**Issue by tanahiro** [PredixDev/generator-px-comp#12]
When I execute `yo px-comp`, I got the following error.

```
events.js:163
      throw er; // Unhandled 'error' event

AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-px-comp/app/templates/_HISTORY.md
    at EditionInterface.exports._copySingle (/usr/lib/node_modules/generator-px-comp/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-px-comp/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/lib/node_modules/generator-px-comp/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at PxComponentGenerator.template (/usr/lib/node_modules/generator-px-comp/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at PxComponentGenerator.projectfiles (/usr/lib/node_modules/generator-px-comp/app/index.js:164:10)
    at /usr/lib/node_modules/generator-px-comp/node_modules/yeoman-generator/lib/base.js:429:16
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

The file name in `/usr/lib/node_modules/generator-px-comp/app/templates/` is `_History.md` but `_HISTORY.md` is required. Which file name is correct?

**Comment by mdwragg** [comment]
This is working for me. Can you give me details on your environment please?

* OS
* Node version
* yo cli version

Thanks!

**Comment by tanahiro** [comment]
The following is info on my machine.

```
$ uname -a
Linux 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
$ yo --version
1.8.5
$ npm --version
4.1.2
$ npm list -g generator-px-comp
/usr/lib
└── generator-px-comp@0.3.17
```

When I rename the file from `_Histroy.md` to `_HISTORY.md`, it worked actually fine.

Thanks.
